// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDat0mgi1rSvSGeELozqQU916isprUYwdc',
    appId: '1:470914911392:web:8465897e2f31c831f4cdc5',
    messagingSenderId: '470914911392',
    projectId: 'proeyecto-39261',
    authDomain: 'proeyecto-39261.firebaseapp.com',
    storageBucket: 'proeyecto-39261.firebasestorage.app',
    measurementId: 'G-66RTRPKLV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuK6LtpsN0TYo4Zja7VeiK_GbYWDc0u0',
    appId: '1:470914911392:android:83ae11719bc8b67ff4cdc5',
    messagingSenderId: '470914911392',
    projectId: 'proeyecto-39261',
    storageBucket: 'proeyecto-39261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKBoQeMJmTw_bfj-J00HoHudiv61qE9Y',
    appId: '1:470914911392:ios:16197e14d86bf3f7f4cdc5',
    messagingSenderId: '470914911392',
    projectId: 'proeyecto-39261',
    storageBucket: 'proeyecto-39261.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKBoQeMJmTw_bfj-J00HoHudiv61qE9Y',
    appId: '1:470914911392:ios:16197e14d86bf3f7f4cdc5',
    messagingSenderId: '470914911392',
    projectId: 'proeyecto-39261',
    storageBucket: 'proeyecto-39261.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDat0mgi1rSvSGeELozqQU916isprUYwdc',
    appId: '1:470914911392:web:ea4426fa53b1310bf4cdc5',
    messagingSenderId: '470914911392',
    projectId: 'proeyecto-39261',
    authDomain: 'proeyecto-39261.firebaseapp.com',
    storageBucket: 'proeyecto-39261.firebasestorage.app',
    measurementId: 'G-1J5GGJPW6Q',
  );

}